version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=rentme'
      - 'POSTGRES_DB=rentme_account'
      - 'TZ=Europe/Israel'
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  eureka:
    image: morgandima87/eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - spring
    depends_on:
      - zipkin
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  apigw:
    image: morgandima87/apigw:latest
    container_name: apigw
    ports:
      - "8765:8765"
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rentme-service:
    image: morgandima87/rentme-service:latest
    container_name: 'rentme-service'
    ports:
      - "15000:15000"
    networks:
      - postgres
      - spring
    restart: always
    depends_on:
      - zipkin
      - eureka
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  google-service:
    image: morgandima87/google-service:latest
    container_name: 'google-service'
#    ports:
#      - "8085:8085"
    networks:
      - spring
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - spring

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
#  rentme-service:
#    driver: bridge
#  googleservice:
#    driver: bridge