spring:
  application:
    name: apigw

server:
  port: 8765

  zipkin:
    base-url: http://zipkin:9411

  cloud:
    gateway:
      routes:
        - id: google-service
          uri: lb://GOOGLE-SERVICE
          predicates:
            - Path=/api/v1/create-candidates/**

        - id: rentme-service
          uri: lb://RENTME-SERVICE
          predicates:
            - Path=/jwt/register/**

        - id: rentme-servicefirst_name
          uri: lb://RENTME-SERVICE
          predicates:
            - Path=/security/getAllAccounts/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

