spring:
  application:
    name: apigw

  zipkin:
    base-url: http://127.0.0.1:9411

  cloud:
    gateway:
      routes:
        - id: google-service
          uri: lb://GOOGLE-SERVICE
          predicates:
            - Path=/api/v1/create-candidates/**

        - id: rentme-service
          uri: lb://RENTME-SERVICE
          predicates:
            - Path=/jwt/register/**

        - id: rentme-service
          uri: lb://RENTME-SERVICE
          predicates:
            - Path=/security/getAllAccounts/**

        - id: rentme-service
          uri: lb://RENTME-SERVICE
          predicates:
            - Path=/security/removeAccount/**
server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true