spring:
  application:
    name: eureka_server_rentme

  zipkin:
    base-url: http://127.0.0.1:9411

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

