spring:
  application:
    name: google-service

  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

rabbitmq:
    exchanges:
        internal: internal.exchange
    queues:
        notification: googleservice.queue
    routing-keys:
        internal-notification: internal.googleservice.routing-key

